# Generated by Django 5.1.1 on 2024-09-09 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('hidden_login', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_link', models.URLField(max_length=255)),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='admin_panel.user')),
            ],
        ),
    ]
