# Generated by Django 5.1.1 on 2024-09-09 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_user_hall_id_alter_project_hall_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hall_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='admin_panel.user'),
        ),
    ]
