# Generated by Django 5.1.1 on 2024-09-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_project_hall_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hall_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hall_id',
            field=models.IntegerField(),
        ),
    ]
