# Generated by Django 5.1.1 on 2024-09-09 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_user_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hall_id',
        ),
    ]
