# Generated by Django 5.1.1 on 2024-09-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_remove_user_hall_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hall_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
