# Generated by Django 5.1.1 on 2024-09-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_user_hall_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='webapp_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
